[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "labdatautils"
version = "0.1.2"
description = "Experimental data utilities: error propagation and LaTeX table generator"
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "Pablo Castro Perez", email = "pbl.castroperez@gmail.com"}]
license = { text = "MIT" }
dependencies = ["numpy>=1.22"]

[project.urls]
Homepage = "https://github.com/Pablo-CastroPerez/labdatautils"
BugTracker = "https://github.com/Pablo-CastroPerez/labdatautils/issues"

[tool.setuptools.packages.find]
where = ["src"]
include = ["labdatautils*"]
