[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fragment-api-py"
version = "1.1.0"
authors = [
    {name = "S1qwy", email = "amirhansuper75@gmail.com"},
]
description = "Python client for Fragment API (fragment.com)"
readme = "PYPI_README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.25.1",
    "dataclasses>=0.6;python_version<'3.7'",
]

[project.urls]
Homepage = "https://github.com/S1qwy/fragment-api-py"
Bug-Reports = "https://github.com/S1qwy/fragment-api-py/issues"