[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rapidllm"
version = "0.5.0"
description = "A small framework for building predictable multi-tool LLM agents."
authors = [
    { name = "Patrick Tuyizere", email = "you@example.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "litellm>=0.1.0"
]

[project.urls]
Homepage = "https://github.com/Patk-Tuy/rapidllm"
Repository = "https://github.com/Patk-Tuy/rapidllm"

[tool.setuptools.packages.find]
where = ["."]