[tool.poetry]
name = "asgardeo"
version = "0.2.1" 
description = "Python SDK for Asgardeo"
authors = ["Thilina Senarath <thilinas@wso2.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "asgardeo", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
httpx = "^0.28.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


