[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mlb_odds_scraper"
version = "0.1.18"
authors = [
  { name="Oronto", email="vile319@gmail.com" },
]
description = "A package for scraping MLB odds data from OddsPortal"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas>=1.0.0",
    "selenium>=4.0.0",
    "stealthenium>=0.1.0",
    "sqlalchemy>=1.4.0",
    "MLB-StatsAPI>=1.0.0"
]

[project.urls]
"Homepage" = "https://github.com/Oronto/mlb_odds_scraper"
"Bug Tracker" = "https://github.com/Oronto/mlb_odds_scraper/issues" 