[tool.poetry]
name = "ai-application-gateway"
version = "0.1.1"
description = "API看板服务"
authors = ["GDX <guandianxi@sensedai.ai>"]
readme = "README.md"
packages = [
    { include = "ai_gateway" }
]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
uvicorn = "^0.34.0"
fastapi = "^0.115.6"
loguru = "^0.7.3"
httpx = "^0.28.1"
anyio = "^4.8.0"
aiohttp = "^3.11.11"
dynaconf = "^3.2.6"
lazify = "^0.4.0"
starlette = "^0.41.3"
sse-starlette = "^2.2.1"
requests = "^2.32.3"
aiomysql = "^0.2.0"
alembic = "^1.14.0"
sqlalchemy = "^2.0.37"
python-jose = "^3.3.0"
pyyaml = "^6.0.2"
shortuuid = "^1.0.13"
sqlmodel = "^0.0.22"
pymysql = "^1.1.1"
greenlet = "^3.1.1"
pydantic = "^2.10.6"
prometheus-fastapi-instrumentator = "^7.0.2"
limiter = "^0.5.0"
elasticsearch = "^8.17.1"
minio = "^7.2.15"
python-multipart = "^0.0.20"
aioboto3 = "^14.0.0"
redis = "^5.2.1"
apscheduler = "^3.11.0"
croniter = "^6.0.0"
pandas = "^2.2.3"
pypinyin = "^0.54.0"
python-pptx = "^1.0.2"
fastmcp = "^2.7.1"
fastapi-mcp = "^0.3.4"
oracledb = "^3.1.0"

[[tool.poetry.source]]
name = "bfsu"
url = "https://mirrors.bfsu.edu.cn/pypi/web/simple/"
priority = "primary"

#[[tool.poetry.source]]
#name = "citic"
#url = "http://repo.citicsinfo.com/repository/pip/simple/"
#priority = "primary"
#
#[[tool.poetry.source]]
#name = "aliyun"
#url = "http://mirrors.cloud.aliyuncs.com/pypi/simple/"
#priority = "supplemental"

[tool.poetry.scripts]
ai-gateway = "ai_gateway.main:main"

[tool.poetry.group.dev.dependencies]
black = "^23.12.1"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[tool.pylint.format]
max-line-length = 140

[tool.isort]
profile = "black"

