[package]
name = "aoe2rec"
description = "Library to parse Age of Empires II: Definitive Edition recorded games"
license = "MIT"
version = "0.2.5"
edition = "2021"
readme = "README.md"

[dependencies]
binrw = "0.14.1"
bytes = { version = "1.8.0", features = ["std"] }
serde = { version = "1.0.214", features = ["derive"] }
yazi = "0.2.0"
