[project]
name = "talentro-definitions"
version = "0.11.5"
description = "This package contains all models and data structures for Talentro"
authors = [
    { name = "Emiel van Essen", email = "emiel@marksmen.nl"}
]
license = { text = "Proprietary" }
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sqlalchemy (>=2.0.38,<3.0.0)",
    "sqlmodel (>=0.0.24,<0.0.25)",
    "fastapi (>=0.115.14,<0.116.0)"
]


[tool.poetry]
packages = [
    {include = "talentro", from = "src"}
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
