[project]
name = "unboil-sqlalchemy-types"
version = "0.1.4"
description = "A library to expand SQLAlchemy types."
readme = "README.md"
authors = [
    { name = "eyueldk" }
]
requires-python = ">=3.9"
dependencies = [
    "sqlalchemy>=2.0.0",
]

keywords = ["unboil", "types", "pydantic", "sqlalchemy"]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
homepage = "https://github.com/eyueldk/unboil-sqlalchemy-types"
repository = "https://github.com/eyueldk/unboil-sqlalchemy-types"

[project.optional-dependencies]
pydantic = [
    "pydantic>=2.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/unboil_sqlalchemy_types"]
