[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "studr"
version = "0.3.1"
description = "im gonna add a description later"
readme = "README.md"
authors = [{name = "fr33 / Emirhan", email = "Emirhan.07274@gmail.com"}]
license = {text = "GPL-3.0-or-later"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Utilities",
    "Topic :: System :: Monitoring",
    "Topic :: Multimedia :: Graphics :: Graphics Conversion",
    "Environment :: Console",
]
requires-python = ">=3.8"
dependencies = [
    "click>=8.0.0",
    "art>=6.0",
    "rich>=13.0.0", 
    "pyfiglet>=0.8.0",
]
keywords = ["stopwatch", "timer", "ascii", "art", "terminal", "timer", "cli"]

[project.urls]
Homepage = "https://github.com/Emirhan-7274/studr"
Repository = "https://github.com/Emirhan-7274/studr"
Issues = "https://github.com/Emirhan-7274/studr/issues"

[project.scripts]
studr = "studr:main"

[tool.setuptools.packages.find]
include = ["studr*"]

[tool.setuptools.package-data]
studr = ["*.txt", "*.md"]