[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "TUI_pygame"
version = "0.1.1"
authors = [
    { name = "liujunyi", email = "liujunyi0702@petalmail.com" }
]
description = "A library for implementing something similar to Pygame in the command line."
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.setuptools]
packages = ["TUI_pygame"]
