[project]
name = "image-mcp"
version = "0.1.1"
description = "A simple MCP server that loads images from a local path or HTTP/HTTPS URL"
readme = "README.md"
authors = [
    {name = "Abhay Deshpande", email = "a.deshpande012@gmail.com"},
]
maintainers = [
    {name = "Abhay Deshpande", email = "a.deshpande012@gmail.com"},
]
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.12.4",
    "pillow>=11.3.0",
]
license = { file = "LICENSE" }
keywords = [
    "mcp",
    "model context protocol",
    "image",
    "ai",
    "agent",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Utilities",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Natural Language :: English",
]

[project.urls]
Homepage = "https://github.com/abhaybd/Image-MCP"
Repository = "https://github.com/abhaybd/Image-MCP"

[project.scripts]
image-mcp = "main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["main"]
