[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ehnpy"
version = "0.1.1"
description = "A Python package for fetching data from the EnvriHub Next (EHN) project."
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "pandas",
    "requests",
    "jupyter",
    "shapely",
    "matplotlib",
    "pillow",
    "argopy",
    "numpy",
     "cartopy",
    "SPARQLWrapper",
    "erddapy",
    "pyarrow",
    "icoscp_core",
]

[project.urls]
Homepage = "https://gitlab.a.incd.pt/envri-hub-next/ehnpy"


[tool.setuptools.packages.find]
include = ["*"]
