[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vibepython"
dynamic = ["version"]
authors = [{ name = "OldTyT" }]
description = "ðŸš€ Python vibe: Unleash the Magic of AI-Powered Coding Wizardry! ðŸŒŸ"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "openai>=1.56.0,<2.0.0",
    "loguru>=0.7.0,<1.0.0",
    "pydantic>=2.8.0,<3.0.0",
    "pydantic-settings>=2.4.0,<3.0.0",
    "pydantic_core>=2.20.0,<3.0.0",
    "g4f[slim]>=0.6.0.1,<0.7.0.0"
]
# features = ["all"]

[tool.hatch.version]
path = "vibepython/__init__.py"

[project.scripts]
vibepython = "vibepython.main:main"

[project.urls]
"Homepage" = "https://github.com/oldtyt/vibepython"
"Source" = "https://github.com/oldtyt/vibepython"

[tool.hatch.build]
exclude = [
    "/resources",
]
