[build-system]
requires = [
    "hatchling>=1.27.0"
]
build-backend = "hatchling.build"

[project]
name = "pypomes_jwt"
version = "1.2.4"
authors = [
  { name="GT Nunes", email="wisecoder01@gmail.com" }
]
description = "A collection of Python pomes, penyeach (JWT module)"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "cryptography>=45.0.6",
    "Flask>=3.1.1",
    "PyJWT>=2.10.1",
    "pypomes_core>=2.6.5",
    "pypomes_db>=2.4.8"
]

[project.urls]
"Homepage" = "https://github.com/TheWiseCoder/PyPomes-JWT"
"Bug Tracker" = "https://github.com/TheWiseCoder/PyPomes-JWT/issues"
