
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "boitrann"
version = "0.1.4"
# dynamic = [
#   'version'
# ]
description = 'Some useful utilities for data structures'
readme = 'README.md'
requires-python = ">= 3.8"

authors = [
    { name = "Tran Quoc Dat", email = "dat.tq6141@gmail.com" },
]
maintainers = [
  {name = "Tran Quoc Dat", email = "dat.tq6141@gmail.com"},
]

license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
repository = 'https://github.com/boitrann/boitrann'

[tool.setuptools_scm]
version_scheme = "incremental"
