[build-system]
requires = ["hatchling>=1.24", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "coords-nsga2"
dynamic = ["version"]
description = "A Python library implementing a coordinate-based NSGA-II for multi-objective optimization."
authors = [
    {name = "Xiaofeng Zhang", email = "xiaofeng1001@outlook.com"}
]
dependencies = [
    "numpy>=1.23",
    "tqdm>=4",
    "shapely>=2",
    "matplotlib"
]
requires-python = ">= 3.9"
readme = { file = "README.md", content-type = "text/markdown" }
license = {text = "MIT"}
keywords = ['optimization',"nsga2","coordinates","genetic-algorithm"]

[project.urls]
Homepage = "https://github.com/ZXF1001/coords-nsga2"

[tool.hatch.version]
source = "vcs"
tag-pattern = "v(?P<version>.*)"

[project.optional-dependencies]
test = [
  "pytest>=8.2",
  "pytest-cov>=5",
  "coverage[toml]>=7.5",
  "hypothesis>=6.100",
  "ruff>=0.11",
  "pre-commit>=3.7",
  "scipy"
]

# pytest 相关
[tool.pytest.ini_options]
addopts = "--cov=coords_nsga2 --cov-report=term-missing"
testpaths = ["tests"]

# coverage 相关
[tool.coverage.run]
branch  = true
source  = ["coords_nsga2"]

[tool.coverage.report]
show_missing = true
fail_under   = 80

[tool.hatch.envs.dev]
dependencies = ["coords-nsga2[test]"]

[tool.hatch.envs.dev.scripts]
test = "pytest -q"
cov  = "pytest"
fmt  = "ruff check --fix coords_nsga2 tests"
