[project]
name = "openbase"
dynamic = ["version"]
description = "Openbase Django Meta-Server"
authors = [{ name = "Gabe Montague", email = "gabemontague@outlook.com" }]
dependencies = [
    "Django==4.2.0",
    "djangorestframework==3.14.0",
    "django-cors-headers==4.0.0",
    "python-dotenv==1.1.1",
    "click==8.2.1",
    "gunicorn==21.0.0",
    "uvicorn==0.23.0",
    "requests==2.32.4",
    "djangorestframework-dataclasses==1.4.0",
    "whitenoise==6.9.0",
    "channels==4.2.2",
    "channels-redis==4.3.0",
    "boilersync==1.1.1",
    "vscode-multi==2.0.0",
    "watchdog==6.0.0",
]

[project.scripts]
openbase = "openbase.core.cli.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["openbase"]
include = ["openbase/static/**/*", "openbase/entrypoint/manage.py"]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "openbase/_version.py"
