[project]
name = "project-work-summary-mcp"
version = "0.0.1-dev"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "wangwenbin", email = "wangwenbin@gwm.cn" }
]
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.13.0",
]

[project.scripts]
project-work-summary-mcp = "project_work_summary_mcp:main"

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"
