[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "microalpha"
version = "0.2.0"
description = "A Python library for analyzing ultra-high-frequency tick data and discovering micro-alpha trading signals."
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Amaya Joshi" }
]
dependencies = [
    "pandas>=1.5",
    "numpy>=1.21"
]
requires-python = ">=3.9"

[project.optional-dependencies]
eda = [
    "matplotlib>=3.5",
    "seaborn>=0.11"
]

[project.scripts]
# Removed unused scripts

[tool.setuptools]
packages = ["microalpha"]

[project.urls]
Homepage = "https://github.com/amaya-j/MicroAlpha.git"
Issues = "https://github.com/amaya-j/MicroAlpha.git/issues"