[build-system]
requires = ["setuptools>=61.0","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "securefilecrypt"
dynamic = ["version"]
description = "Secure File Encryption Library"
readme = "README.md"
requires-python = ">=3.7"
license = { file = "LICENSE" }
authors = [
    { name = "diegomarin75", email = "diegomarin75@gmail.com" }
]
dependencies = ["cryptography>=45.0.6"]

[tool.setuptools.dynamic]
version = { attr = "securefilecrypt.__version__" }

[project.urls]
Homepage = "https://github.com/diegomarin75-work/SecureFileCrypt"
Issues = "https://github.com/diegomarin75-work/SecureFileCrypt/issues"

[project.scripts]
sfcrypt = "securefilecrypt.cli:main"