[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ansible-extra-tools"
version = "0.2.0"
description = "Extra tools for Ansible"
authors = [{name = "Dan Griffin"}]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
dependencies = ["ansible-core >= 2.15"]
classifiers = [
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: System :: Systems Administration",
    "Topic :: Utilities",
]
keywords = ["ansible"]

[project.scripts]
ansible-role = "ansible_extra_tools.role:main"

[project.urls]
homepage = "https://github.com/dwgriffin/ansible-extra-tools"
repository = "https://github.com/dwgriffin/ansible-extra-tools"
