[build-system]
requires = ["uv_build >= 0.7.19, <0.9.0"]
build-backend = "uv_build"

[project]
name = "ppptoolbox"
version = "0.0.4"
authors = [
  { name="Ruslan AÄŸalarov", email="ruslan.a@pashapay.az" },
]
description = "PashaPay Python Toolbox"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = { text = "MIT" }

[project.urls]
Homepage = "https://github.com/m10-payments/python-toolbox"