[project]
name = "depzip"
version = "1.1"
description = "A small library for zipping Python application dependencies"
authors = [{name = "Pavel Demin"}]
dependencies = ["dllist"]
requires-python = ">=3.12"
readme = "README.md"
license = "MIT"

[project.urls]
Homepage = "https://github.com/pavel-demin/depzip"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
depzip = ["*.exe"]
