[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lizeur"
authors = [{name = "Charlie Boutier", email = "charlie.boutier7@gmail.com"}]
version = "0.1.3"
description = "Lizeur is a MCP server to be able to get content from PDFs."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
keywords = ["mcp", "pdf", "ocr", "mistral", "ai", "model-context-protocol"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Markup",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "mcp[cli]>=1.12.4",
    "mistralai>=0.0.10",
]
urls = {Homepage = "https://github.com/SilverBzH/lizeur", Repository = "https://github.com/SilverBzH/lizeur", Issues = "https://github.com/SilverBzH/lizeur/issues"}

[project.scripts]
lizeur = "main:main"

[tool.hatch.build.targets.wheel]
packages = ["."]