[project]
name = "fabricengineer-py"
version = "1.0.3"
description = "Package for Fabric Engineers"
readme = "README.md"
authors = [
    { name = "Enrico Goerlitz", email = "private.email@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "delta-spark==3.2.0",
    "pyspark==3.5.0",
    "pytest>=8.4.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra -q"
testpaths = ["src/tests"]
pythonpath = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src/fabricengineer"]
