[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[project]
name = "always_note"
version = "0.0.2"
authors = [
  { name="Martin O'Hanlon", email="martin@ohanlonweb.com" },
]
description = "An always-on screen note"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["guizero"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.scripts]
always_note = "always_note:main"