[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "timedc"
version = "0.1.3"
description = "Утилита для генерации Discord timestamp"
authors = [{ name = "Prostoron" }]
license = { file = "LICENSE" }
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"

[tool.setuptools]
packages = ["timedc"]
