[build-system]
requires = [
  "setuptools>=65",
]
build-backend = "setuptools.build_meta"

[project]
name = "duo-ai"
version = "1.0.0"
requires-python = ">=3.8"
description = "DuoAI: Two-System AI Agents"
readme = "README.md"
dependencies = [
  "omegaconf>=2.3.0",
  "gym>=0.26.2",
  "torch>=2.1.2",
  "wandb>=0.19.11",
  "scikit-learn",
  "numba",
]

[project.optional-dependencies]
docs = [
  "sphinx",
  "sphinx-autoapi",
  "sphinx_copybutton",
  "furo",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["duo_ai", "duo_ai.*"]
